/**
 * Initialization wizard for LongerAgent.
 *
 * Provides an interactive first-run setup experience using @inquirer/prompts.
 * Supports Ctrl+C / ESC to go back to the previous step.
 */

import { existsSync, mkdirSync, writeFileSync, cpSync } from "node:fs";
import { join, dirname } from "node:path";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import { checkbox, select, input, confirm } from "@inquirer/prompts";
import * as yaml from "js-yaml";
import { LONGERAGENT_HOME_DIR } from "./config.js";
import {
  PROVIDER_PRESETS,
  buildProviderPresetRawConfig,
  type ProviderPreset,
  type ProviderPresetModel,
} from "./provider-presets.js";

// ------------------------------------------------------------------
// Wizard result
// ------------------------------------------------------------------

export interface WizardResult {
  configPath: string;
  templatesPath: string;
  skillsPath: string;
}

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------

function getBundledAssetsDir(): string {
  const thisFile = fileURLToPath(import.meta.url);
  return join(dirname(thisFile), "..");
}

function isUserCancel(err: unknown): boolean {
  if (!err || typeof err !== "object") return false;
  // @inquirer/prompts throws ExitPromptError on Ctrl+C
  return (err as any).name === "ExitPromptError" ||
    (err as any).code === "ERR_USE_AFTER_CLOSE";
}

interface SelectedModel {
  configName: string;
  rawConfig: Record<string, unknown>;
}

function generateConfigYaml(
  defaultModelName: string,
  models: SelectedModel[],
): string {
  const payload: Record<string, unknown> = {
    default_model: defaultModelName,
    models: Object.fromEntries(
      models.map((model) => [model.configName, model.rawConfig]),
    ),
  };

  const lines: string[] = [
    "# LongerAgent configuration",
    "# Generated by 'longeragent init'",
    "",
    yaml.dump(payload, { lineWidth: -1 }).trimEnd(),
    "",
  ];

  return lines.join("\n");
}

// ------------------------------------------------------------------
// Step functions (each returns result or throws on cancel)
// ------------------------------------------------------------------

async function stepSelectProviders(): Promise<string[]> {
  return await checkbox({
    message: "Select providers (space to toggle, enter to confirm)",
    choices: PROVIDER_PRESETS.map((p) => {
      const envSet = process.env[p.envVar] ? " ✓ key detected" : "";
      return {
        name: `${p.name}${envSet}`,
        value: p.id,
      };
    }),
    required: true,
  });
}

/**
 * Derive a config name from a model ID.
 * e.g. "anthropic/claude-sonnet-4.6" → "or-claude-sonnet-4.6"
 *      "openai/gpt-5.4" → "or-gpt-5.4"
 */
function openRouterConfigName(model: ProviderPresetModel): string {
  const base = model.key.includes("/") ? model.key.split("/").pop()! : model.key;
  return `or-${base.replace(/[^a-z0-9.-]/gi, "-").toLowerCase()}`;
}

async function stepConfigureProvider(provider: ProviderPreset): Promise<SelectedModel[]> {
  // API key
  const envValue = process.env[provider.envVar];
  let apiKey: string;

  if (envValue) {
    const choice = await select({
      message: `${provider.name}: ${provider.envVar} detected in environment`,
      choices: [
        { name: "Use it", value: "use" },
        { name: "Enter a different key for LongerAgent", value: "new" },
      ],
    });
    if (choice === "use") {
      apiKey = `\${${provider.envVar}}`;
    } else {
      apiKey = await input({ message: `${provider.name}: Paste API key` });
    }
  } else {
    apiKey = await input({
      message: `${provider.name}: Paste API key (or Enter to set ${provider.envVar} later)`,
    });
    if (!apiKey) {
      apiKey = `\${${provider.envVar}}`;
    }
  }

  // Model selection — OpenRouter supports multi-select (multi-model gateway)
  if (provider.id === "openrouter") {
    const selectedModelIds = await checkbox({
      message: `${provider.name}: Select models (space to toggle, enter to confirm)`,
      choices: provider.models.map((m) => ({
        name: m.label,
        value: m.key,
      })),
      required: true,
    });

    return selectedModelIds.map((modelId) => ({
      configName: openRouterConfigName(
        provider.models.find((model) => model.key === modelId)!,
      ),
      rawConfig: buildProviderPresetRawConfig(
        provider.id,
        provider.models.find((model) => model.key === modelId)!,
        apiKey,
      ),
    }));
  }

  // Other providers — single model selection
  const selectedModelId = await select({
    message: `${provider.name}: Select model`,
    choices: provider.models.map((m) => ({
      name: m.label,
      value: m.key,
    })),
  });

  const selectedModel = provider.models.find((model) => model.key === selectedModelId)!;
  const configName = `my-${provider.id.replace(/[^a-z0-9]/g, "")}`;
  return [{
    configName,
    rawConfig: buildProviderPresetRawConfig(provider.id, selectedModel, apiKey),
  }];
}

async function stepSelectDefault(models: SelectedModel[]): Promise<string> {
  if (models.length <= 1) return models[0]?.configName ?? "";
  return await select({
    message: "Select default model",
    choices: models.map((m) => ({
      name: `${m.configName} (${m.rawConfig["provider"]}/${m.rawConfig["model"]})`,
      value: m.configName,
    })),
  });
}

// ------------------------------------------------------------------
// Main wizard — state machine with back support
// ------------------------------------------------------------------

const enum Step { CHECK_EXISTING, SELECT_PROVIDERS, CONFIGURE_PROVIDERS, SELECT_DEFAULT, WRITE }

export async function runInitWizard(): Promise<WizardResult> {
  const homeDir = join(homedir(), LONGERAGENT_HOME_DIR);
  const configPath = join(homeDir, "config.yaml");

  console.log();
  console.log("  ╔══════════════════════════════════════╗");
  console.log("  ║    Welcome to LongerAgent Setup!     ║");
  console.log("  ╚══════════════════════════════════════╝");
  console.log("  (Ctrl+C to go back, double Ctrl+C to quit)\n");

  let step: Step = existsSync(configPath) ? Step.CHECK_EXISTING : Step.SELECT_PROVIDERS;
  let selectedProviderIds: string[] = [];
  let models: SelectedModel[] = [];
  let providerIdx = 0;
  let defaultModelName = "";
  // Track how many models each provider step added (for correct Ctrl+C rollback)
  const modelsPerStep: number[] = [];

  while (step !== Step.WRITE) {
    try {
      switch (step) {
        case Step.CHECK_EXISTING: {
          console.log(`  Existing config found: ${configPath}`);
          const useExisting = await confirm({
            message: "Use existing configuration?",
            default: true,
          });
          if (useExisting) {
            console.log("\n  ✓ Using existing configuration.\n");
            return {
              configPath,
              templatesPath: join(homeDir, "agent_templates"),
              skillsPath: join(homeDir, "skills"),
            };
          }
          step = Step.SELECT_PROVIDERS;
          break;
        }

        case Step.SELECT_PROVIDERS: {
          selectedProviderIds = await stepSelectProviders();
          models = [];
          providerIdx = 0;
          step = Step.CONFIGURE_PROVIDERS;
          break;
        }

        case Step.CONFIGURE_PROVIDERS: {
          const selectedProviders = PROVIDER_PRESETS.filter((p) =>
            selectedProviderIds.includes(p.id),
          );
          if (providerIdx >= selectedProviders.length) {
            step = Step.SELECT_DEFAULT;
            break;
          }
          console.log();
          const results = await stepConfigureProvider(selectedProviders[providerIdx]);
          models.push(...results);
          modelsPerStep.push(results.length);
          providerIdx++;
          // Stay in CONFIGURE_PROVIDERS until all done
          if (providerIdx >= selectedProviders.length) {
            step = Step.SELECT_DEFAULT;
          }
          break;
        }

        case Step.SELECT_DEFAULT: {
          defaultModelName = await stepSelectDefault(models);
          step = Step.WRITE;
          break;
        }
      }
    } catch (err) {
      if (!isUserCancel(err)) throw err;

      // Go back one step
      switch (step) {
        case Step.CHECK_EXISTING:
          // Can't go further back — quit
          console.log("\n  Setup cancelled.\n");
          throw err;

        case Step.SELECT_PROVIDERS:
          if (existsSync(configPath)) {
            step = Step.CHECK_EXISTING;
          } else {
            console.log("\n  Setup cancelled.\n");
            throw err;
          }
          break;

        case Step.CONFIGURE_PROVIDERS:
          if (providerIdx > 0) {
            // Go back to previous provider — pop all models it added
            const popCount = modelsPerStep.pop() ?? 1;
            models.splice(models.length - popCount, popCount);
            providerIdx--;
          } else {
            // Go back to provider selection
            step = Step.SELECT_PROVIDERS;
          }
          break;

        case Step.SELECT_DEFAULT: {
          // Go back to re-configure the last provider — pop all models it added
          const popCount = modelsPerStep.pop() ?? 1;
          models.splice(models.length - popCount, popCount);
          providerIdx = Math.max(0, providerIdx - 1);
          step = Step.CONFIGURE_PROVIDERS;
          break;
        }
      }
      console.log();
    }
  }

  // Write config
  mkdirSync(homeDir, { recursive: true });
  const configContent = generateConfigYaml(defaultModelName, models);
  writeFileSync(configPath, configContent, "utf-8");

  // Copy bundled templates, prompts, and skills
  const assetsDir = getBundledAssetsDir();
  const templatesPath = join(homeDir, "agent_templates");
  const promptsPath = join(homeDir, "prompts");
  const skillsPath = join(homeDir, "skills");

  const bundledTemplates = join(assetsDir, "agent_templates");
  const bundledPrompts = join(assetsDir, "prompts");
  const bundledSkills = join(assetsDir, "skills");

  if (existsSync(bundledTemplates) && !existsSync(templatesPath)) {
    cpSync(bundledTemplates, templatesPath, { recursive: true });
  }
  if (existsSync(bundledPrompts) && !existsSync(promptsPath)) {
    cpSync(bundledPrompts, promptsPath, { recursive: true });
  }
  if (existsSync(bundledSkills) && !existsSync(skillsPath)) {
    cpSync(bundledSkills, skillsPath, { recursive: true });
  }

  // Summary
  console.log();
  console.log("  ✓ Configuration saved");
  console.log(`    Config:    ${configPath}`);
  console.log(`    Templates: ${templatesPath}`);
  console.log(`    Skills:    ${skillsPath}`);
  console.log();
  console.log(`  Default model: ${defaultModelName}`);

  // Show env var status
  const selectedPresets = PROVIDER_PRESETS.filter((p) =>
    models.some((m) => m.rawConfig["provider"] === p.id),
  );
  const missing: string[] = [];
  for (const p of selectedPresets) {
    if (process.env[p.envVar]) {
      console.log(`  ✓ ${p.envVar}`);
    } else {
      console.log(`  ✗ ${p.envVar} (not set)`);
      missing.push(p.envVar);
    }
  }

  if (missing.length > 0) {
    console.log();
    console.log("  Set the missing keys before starting:");
    for (const v of missing) {
      console.log(`    export ${v}="your-key-here"`);
    }
  }

  console.log();
  console.log("  Run 'longeragent' to start.");
  console.log();

  return { configPath, templatesPath, skillsPath };
}
